/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Saler;

import BEAN.DanhMucBean;
import DAO.HangHoaDAO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author acer
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Color DefaultColor, ClickedColor;

    public MainJFrame() {
        initComponents();
       dashboardControl();
        
    }
    public void dashboardControl(){
         mainScreen.setLayout(new BorderLayout());
        mainScreen.add(new ThongTinNhanVien());
        DefaultColor = new Color(255, 255, 255);
        ClickedColor = new Color(240, 151, 57);
        panelttcn.setBackground(ClickedColor);
        panelbh.setBackground(DefaultColor);
        panelsp.setBackground(DefaultColor);
        paneltkh.setBackground(DefaultColor);
        paneldx.setBackground(DefaultColor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        sideBar2 = new javax.swing.JPanel();
        panelbh = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelsp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        paneldx = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelttcn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        paneltkh = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        mainScreen = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        sideBar2.setBackground(new java.awt.Color(189, 205, 214));

        panelbh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelbhMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelbhMousePressed(evt);
            }
        });

        jLabel1.setText("Bán hàng");

        javax.swing.GroupLayout panelbhLayout = new javax.swing.GroupLayout(panelbh);
        panelbh.setLayout(panelbhLayout);
        panelbhLayout.setHorizontalGroup(
            panelbhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(43, 43, 43))
        );
        panelbhLayout.setVerticalGroup(
            panelbhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbhLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelspMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelspMousePressed(evt);
            }
        });

        jLabel3.setText("Sản phẩm");

        javax.swing.GroupLayout panelspLayout = new javax.swing.GroupLayout(panelsp);
        panelsp.setLayout(panelspLayout);
        panelspLayout.setHorizontalGroup(
            panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelspLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelspLayout.setVerticalGroup(
            panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelspLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        paneldx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneldxMousePressed(evt);
            }
        });

        jLabel4.setText("Đăng xuất");

        javax.swing.GroupLayout paneldxLayout = new javax.swing.GroupLayout(paneldx);
        paneldx.setLayout(paneldxLayout);
        paneldxLayout.setHorizontalGroup(
            paneldxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldxLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneldxLayout.setVerticalGroup(
            paneldxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldxLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelttcn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelttcnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelttcnMousePressed(evt);
            }
        });

        jLabel5.setText("Thông tin cá nhân");

        javax.swing.GroupLayout panelttcnLayout = new javax.swing.GroupLayout(panelttcn);
        panelttcn.setLayout(panelttcnLayout);
        panelttcnLayout.setHorizontalGroup(
            panelttcnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelttcnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelttcnLayout.setVerticalGroup(
            panelttcnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelttcnLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        paneltkh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneltkhMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneltkhMousePressed(evt);
            }
        });

        jLabel6.setText("Thêm khách hàng");

        javax.swing.GroupLayout paneltkhLayout = new javax.swing.GroupLayout(paneltkh);
        paneltkh.setLayout(paneltkhLayout);
        paneltkhLayout.setHorizontalGroup(
            paneltkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltkhLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(20, 20, 20))
        );
        paneltkhLayout.setVerticalGroup(
            paneltkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltkhLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sideBar2Layout = new javax.swing.GroupLayout(sideBar2);
        sideBar2.setLayout(sideBar2Layout);
        sideBar2Layout.setHorizontalGroup(
            sideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBar2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelbh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneldx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelttcn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneltkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBar2Layout.setVerticalGroup(
            sideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelttcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelbh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneltkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneldx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainScreen.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainScreenLayout = new javax.swing.GroupLayout(mainScreen);
        mainScreen.setLayout(mainScreenLayout);
        mainScreenLayout.setHorizontalGroup(
            mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );
        mainScreenLayout.setVerticalGroup(
            mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        title.setBackground(new java.awt.Color(147, 166, 174));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(173, 248, 26));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MÀN HÌNH NHÂN VIÊN");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titleLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(38, 38, 38)))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titleLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jLabel2)
                    .addContainerGap(9, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(sideBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sideBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelttcnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelttcnMousePressed
        panelttcn.setBackground(ClickedColor);
        panelbh.setBackground(DefaultColor);
        panelsp.setBackground(DefaultColor);
        paneltkh.setBackground(DefaultColor);
        paneldx.setBackground(DefaultColor);
          ThongTinNhanVien ttnv = new ThongTinNhanVien();
        mainScreen.removeAll();
        mainScreen.revalidate();
        mainScreen.repaint();
        mainScreen.add(ttnv).setVisible(true);
    }//GEN-LAST:event_panelttcnMousePressed

    private void panelbhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbhMousePressed
        panelttcn.setBackground(DefaultColor);
        panelbh.setBackground(ClickedColor);
        panelsp.setBackground(DefaultColor);
        paneltkh.setBackground(DefaultColor);
        paneldx.setBackground(DefaultColor);
         BanHang bh = new BanHang();
        mainScreen.removeAll();
        mainScreen.revalidate();
        mainScreen.repaint();
        mainScreen.add(bh).setVisible(true);
    }//GEN-LAST:event_panelbhMousePressed

    private void panelspMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelspMousePressed
        // TODO add your handling code here:
        panelttcn.setBackground(DefaultColor);
        panelbh.setBackground(DefaultColor);
        panelsp.setBackground(ClickedColor);
        paneltkh.setBackground(DefaultColor);
        paneldx.setBackground(DefaultColor);
         SanPham sp = new SanPham();
         mainScreen.removeAll();
        mainScreen.revalidate();
        mainScreen.repaint();
        mainScreen.add(sp).setVisible(true);
    }//GEN-LAST:event_panelspMousePressed

    private void paneltkhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneltkhMousePressed
        // TODO add your handling code here:
        panelttcn.setBackground(DefaultColor);
        panelbh.setBackground(DefaultColor);
        panelsp.setBackground(DefaultColor);
        paneltkh.setBackground(ClickedColor);
        paneldx.setBackground(DefaultColor);
        ThemKhachHang tkh = new ThemKhachHang();
          mainScreen.removeAll();
        mainScreen.revalidate();
        mainScreen.repaint();
        mainScreen.add(tkh).setVisible(true);
    }//GEN-LAST:event_paneltkhMousePressed

    private void paneldxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneldxMousePressed
        // TODO add your handling code here:
        panelttcn.setBackground(DefaultColor);
        panelbh.setBackground(DefaultColor);
        panelsp.setBackground(DefaultColor);
        paneltkh.setBackground(DefaultColor);
        paneldx.setBackground(ClickedColor);
    }//GEN-LAST:event_paneldxMousePressed

    private void panelbhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbhMouseClicked
        // TODO add your handling code here:

       
    }//GEN-LAST:event_panelbhMouseClicked

    private void panelttcnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelttcnMouseClicked
        // TODO add your handling code here:
      

    }//GEN-LAST:event_panelttcnMouseClicked

    private void panelspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelspMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_panelspMouseClicked

    private void paneltkhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneltkhMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_paneltkhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelThongTinNhanVien;
    private javax.swing.JLabel LabelThongTinNhanVien1;
    private javax.swing.JPanel PanelThongTinNhanVien;
    private javax.swing.JPanel PanelThongTinNhanVien1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainScreen;
    private javax.swing.JPanel panelbh;
    private javax.swing.JPanel paneldx;
    private javax.swing.JPanel panelsp;
    private javax.swing.JPanel paneltkh;
    private javax.swing.JPanel panelttcn;
    private javax.swing.JPanel sideBar;
    private javax.swing.JPanel sideBar1;
    private javax.swing.JPanel sideBar2;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
