/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.QuanLy;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Color DefaultColor, ClickedColor;

    public MainJFrame() {
        initComponents();
        dashboardControl();

    }

    public void dashboardControl() {
        mainScreen.setLayout(new BorderLayout());
        mainScreen.add(new QuanLyNhanVien());
        DefaultColor = new Color(255, 255, 255);
        ClickedColor = new Color(240, 151, 57);
        panelnv.setBackground(ClickedColor);
        panelkh.setBackground(DefaultColor);
        panelsp.setBackground(DefaultColor);
        paneltk.setBackground(DefaultColor);
        panelct.setBackground(DefaultColor);
        paneldx.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        sideBar = new javax.swing.JPanel();
        panelnv = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelkh = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        paneltk = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelsp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelct = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        paneldx = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        mainScreen = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ");
        setBackground(new java.awt.Color(255, 192, 203));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        sideBar.setBackground(new java.awt.Color(189, 205, 214));

        panelnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelnvMousePressed(evt);
            }
        });

        jLabel1.setText("Nhân viên");

        javax.swing.GroupLayout panelnvLayout = new javax.swing.GroupLayout(panelnv);
        panelnv.setLayout(panelnvLayout);
        panelnvLayout.setHorizontalGroup(
            panelnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnvLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelnvLayout.setVerticalGroup(
            panelnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnvLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelkh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelkhMousePressed(evt);
            }
        });

        jLabel3.setText("Khách hàng");

        javax.swing.GroupLayout panelkhLayout = new javax.swing.GroupLayout(panelkh);
        panelkh.setLayout(panelkhLayout);
        panelkhLayout.setHorizontalGroup(
            panelkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelkhLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26))
        );
        panelkhLayout.setVerticalGroup(
            panelkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelkhLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(16, 16, 16))
        );

        paneltk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneltkMousePressed(evt);
            }
        });

        jLabel4.setText("Thống kê");

        javax.swing.GroupLayout paneltkLayout = new javax.swing.GroupLayout(paneltk);
        paneltk.setLayout(paneltkLayout);
        paneltkLayout.setHorizontalGroup(
            paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltkLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneltkLayout.setVerticalGroup(
            paneltkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltkLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelspMousePressed(evt);
            }
        });

        jLabel5.setText("Sản phẩm");

        javax.swing.GroupLayout panelspLayout = new javax.swing.GroupLayout(panelsp);
        panelsp.setLayout(panelspLayout);
        panelspLayout.setHorizontalGroup(
            panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelspLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33))
        );
        panelspLayout.setVerticalGroup(
            panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelspLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelctMousePressed(evt);
            }
        });

        jLabel6.setText("Chi tiêu");

        javax.swing.GroupLayout panelctLayout = new javax.swing.GroupLayout(panelct);
        panelct.setLayout(panelctLayout);
        panelctLayout.setHorizontalGroup(
            panelctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelctLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelctLayout.setVerticalGroup(
            panelctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelctLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        paneldx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneldxMousePressed(evt);
            }
        });

        jLabel7.setText("Đăng xuất");

        javax.swing.GroupLayout paneldxLayout = new javax.swing.GroupLayout(paneldx);
        paneldx.setLayout(paneldxLayout);
        paneldxLayout.setHorizontalGroup(
            paneldxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldxLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneldxLayout.setVerticalGroup(
            paneldxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldxLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneltk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneldx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneltk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneldx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainScreen.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainScreenLayout = new javax.swing.GroupLayout(mainScreen);
        mainScreen.setLayout(mainScreenLayout);
        mainScreenLayout.setHorizontalGroup(
            mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );
        mainScreenLayout.setVerticalGroup(
            mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        title.setBackground(new java.awt.Color(147, 166, 174));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(173, 248, 26));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MÀN HÌNH QUẢN LÝ");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1089, Short.MAX_VALUE)
            .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titleLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(38, 38, 38)))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titleLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jLabel2)
                    .addContainerGap(9, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelnvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelnvMousePressed
        // TODO add your handling code here:
        panelnv.setBackground(ClickedColor);
        panelkh.setBackground(DefaultColor);
        panelsp.setBackground(DefaultColor);
        paneltk.setBackground(DefaultColor);
        panelct.setBackground(DefaultColor);
        paneldx.setBackground(DefaultColor);
        QuanLyNhanVien qlnv = new QuanLyNhanVien();
        mainScreen.removeAll();
        mainScreen.revalidate();
        mainScreen.repaint();
        mainScreen.add(qlnv).setVisible(true);
    }//GEN-LAST:event_panelnvMousePressed

    private void panelkhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelkhMousePressed
        // TODO add your handling code here:
        panelnv.setBackground(DefaultColor);
        panelkh.setBackground(ClickedColor);
        panelsp.setBackground(DefaultColor);
        paneltk.setBackground(DefaultColor);
        panelct.setBackground(DefaultColor);
        paneldx.setBackground(DefaultColor);
        QuanLyKhachHang qlkh = new QuanLyKhachHang();
        mainScreen.removeAll();
        mainScreen.revalidate();
        mainScreen.repaint();
        mainScreen.add(qlkh).setVisible(true);
    }//GEN-LAST:event_panelkhMousePressed

    private void panelspMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelspMousePressed
        // TODO add your handling code here:
        panelnv.setBackground(DefaultColor);
        panelkh.setBackground(DefaultColor);
        panelsp.setBackground(ClickedColor);
        paneltk.setBackground(DefaultColor);
        panelct.setBackground(DefaultColor);
        paneldx.setBackground(DefaultColor);
        QuanLySanPham qlsp = new QuanLySanPham();
        mainScreen.removeAll();
        mainScreen.revalidate();
        mainScreen.repaint();
        mainScreen.add(qlsp).setVisible(true);
    }//GEN-LAST:event_panelspMousePressed

    private void paneltkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneltkMousePressed
        // TODO add your handling code here:
        panelnv.setBackground(DefaultColor);
        panelkh.setBackground(DefaultColor);
        panelsp.setBackground(DefaultColor);
        paneltk.setBackground(ClickedColor);
        panelct.setBackground(DefaultColor);
        paneldx.setBackground(DefaultColor);
        ThongKe tk = new ThongKe();
        mainScreen.removeAll();
        mainScreen.revalidate();
        mainScreen.repaint();
        mainScreen.add(tk).setVisible(true);
    }//GEN-LAST:event_paneltkMousePressed

    private void panelctMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelctMousePressed
        // TODO add your handling code here:
        panelnv.setBackground(DefaultColor);
        panelkh.setBackground(DefaultColor);
        panelsp.setBackground(DefaultColor);
        paneltk.setBackground(DefaultColor);
        panelct.setBackground(ClickedColor);
        paneldx.setBackground(DefaultColor);
        QuanLyChiTieu qlct = new QuanLyChiTieu();
        mainScreen.removeAll();
        mainScreen.revalidate();
        mainScreen.repaint();
        mainScreen.add(qlct).setVisible(true);
    }//GEN-LAST:event_panelctMousePressed

    private void paneldxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneldxMousePressed
        // TODO add your handling code here:
        panelnv.setBackground(DefaultColor);
        panelkh.setBackground(DefaultColor);
        panelsp.setBackground(DefaultColor);
        paneltk.setBackground(DefaultColor);
        panelct.setBackground(DefaultColor);
        paneldx.setBackground(ClickedColor);
    }//GEN-LAST:event_paneldxMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainScreen;
    private javax.swing.JPanel panelct;
    private javax.swing.JPanel paneldx;
    private javax.swing.JPanel panelkh;
    private javax.swing.JPanel panelnv;
    private javax.swing.JPanel panelsp;
    private javax.swing.JPanel paneltk;
    private javax.swing.JPanel sideBar;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
